### ISSUE TITLE
Support for v2 API

### ISSUE THREAD

**Issue by emgrav** [famedly/zitadel-rust-client#14]
Related: famedly/ldap-sync#24

We want to implement the Zitadel v2 API. Instead of using the `zitadel-rust` crate, we will instead create an MVP of a REST API client crate specifically for the v2 API. This means we will manually implement the prerequisite types and call the REST endpoints. This should allow us to circumvent many of the problems we have with the `zitadel-rust` crate, as well as sidestep the future problem of forward proxies with post-hyper-1.x grpc.

## Requirements
* Define appropriate types
* Implementation of service account base client with authentication and token refresh etc
* Appropriate tests
* Documentation

## Steps to implement
* We will start implementing the endpoints we have an immediate need for and get a feel for what kind of abstraction makes sense. https://zitadel.com/docs/apis/resources/user_service_v2/user-service

This would probably make sense to split out into a different crate down the line, but for now I think a separate module in this crate would work.

## User story
As a developer, I want to create users without sending an activation email so users don't get confused when their accounts are provisioned.

```[tasklist]
### Tasks
- [ ] https://github.com/famedly/zitadel-rust-client/issues/15
- [ ] https://github.com/famedly/zitadel-rust-client/issues/16
- [ ] https://github.com/famedly/zitadel-rust-client/issues/17
- [ ] https://github.com/famedly/zitadel-rust-client/issues/18
- [ ] https://github.com/famedly/zitadel-rust-client/issues/19
```

## Reference
https://docs.rs/zitadel/latest/zitadel/api/zitadel/user/v2/index.html
